version: '3'

services:
    pleroma:
        build: ./docker-pleroma
        restart: always
        environment:
            - MIX_ENV=%RUN_MODE%
        volumes:
            - ./config:/opt/pleroma/config
            - ./uploads:/opt/pleroma/uploads
        depends_on:
            - postgres
        ports:
            - '127.0.0.1:4000:4000'
        networks:
            - pleroma

    postgres:
        image: postgres:10.3-alpine
        restart: always
        volumes:
            - ./postgres:/var/lib/postgresql/data
        networks:
            - pleroma

networks:
    pleroma:
